import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

// React 없는 부분
// 검색이 잘 되도록 노출하려면, 시멘틱 태그를 목적에 맞게 사용
// tag : 시멘틱 태그를 목적에 맞게 사용한다.
// h1, title, meta
// 위에 것을 리액트에서는 하기 어렵다.

// react 보다 자동화율이 높은것이 next의 차이점

// 변수 초기화
// src/app/layout.js
export const metadata = { // 이 친구가 없으면 localhost가 제목으로 나온다. // 이것을 이용하면 검색어 우선순위에 오른다.
  title : {
    default: `My Next App`,
    template: `%s | My Next App`, // %s(문자열들), |(union) <= typescript에서 나옴 = 결합과 같은 의미
    // about | My Next App
    // profile | My Next App
    // makeup | My Next App
    // comments | My Next App
  },
  description: "Generated by create next app",
  keyword: ["html", "css", "javascript"]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

